server:
  port: 5001

logging:
  level:
    org:
      springframework: debug
    tech:
      aomi: debug
  pattern:
    console: "[%X{logId}] %clr(%d){blue} [%clr(%-5level){lightgreen}] [%logger{0}] - %msg%n"
    file: "[%X{logId}] %d [%-5level] [%logger{0}] - %msg%n"

spring:
  application:
    name: Core
  main:
    allow-bean-definition-overriding: true
  # Http 配置
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 5000MB
      max-request-size: 5000MB
      location: ${core.rootDir}
  web:
    resources:
      static-locations: "file://${core.rootDir}"
  mvc:
    static-path-pattern: /assets/**
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      ORDER_MAP_ENTRIES_BY_KEYS: true
      WRITE_DATES_AS_TIMESTAMPS: true
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
  data:
    mongodb:
      authentication-database: filexplorer
      database: filexplorer
      username: prod
      auto-index-creation: true

core:
  rootDir: /Users/Sean/workspaces/assets-server/core/fileRoot