server:
  port: 5001
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    internal-proxies: ".*"

logging:
  file:
    max-size: 30MB
    max-history: 0
  level:
    org:
      springframework: debug
    software: debug
    tech:
      aomi: debug
  pattern:
    console: "%clr(%d){blue} [%clr(%-5level){lightgreen}] [%logger{0}] - %msg%n"
    file: "%d [%-5level] [%logger{0}] - %msg%n"

spring:
  application:
    name: Core
  main:
    allow-bean-definition-overriding: true
  # Http 配置
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 50MB
      max-request-size: 50MB
      location: ${core.rootDir}
  resources:
    static-locations: "file://${core.rootDir}"
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      ORDER_MAP_ENTRIES_BY_KEYS: true
      WRITE_DATES_AS_TIMESTAMPS: true
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
  data:
    mongodb:
      host: 101.132.108.155
      port: 30000
      username: dev
      password: dev.com
      database: acquiring
      authentication-database: acquiring

core:
  rootDir: /Users/Sean/tmp